services:
  nest-rest-api:
    image: node:22
    container_name: nest-rest-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: '${NODE_ENV}'
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - nest-rest-network-link
    depends_on:
      - nest-rest-mysql
    entrypoint: ["tail", "-f", "/dev/null"]

  nest-rest-mysql:
    image: mysql:5.7
    container_name: ${DATABASE_HOST}
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: '${DATABASE_NAME}'
      MYSQL_USER: '${DATABASE_USERNAME}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DATABASE_ROOT_PASSWORD}'
    networks:
      - nest-rest-network-link
    volumes:
      - database-data:/var/lib/mysql

networks:
  nest-rest-network-link:
    driver: bridge
    name: nest-rest-network-link

volumes:
  database-data:
    name: nest-rest-mysql-database
